### PR TITLE
Added all Qt imports

### LINKED ISSUE #152: Better support for Qt
Qt is not just a library - it is a framework.

A Qt Application can import(`#include`) any of these classes
[Qt6 Docs - All Classes](https://doc.qt.io/qt-6/classes.html)

All of these classes should be present in [`libraries.json`](https://github.com/codersrank-org/libraries/blob/master/libraries.json) for the repo info extractor to fully detect Qt.

Is there an automated way to do this?

### PR DESCRIPTION
**Pull request by kitswas**
These have been extracted from the Qt documentation at  
https://doc.qt.io/qt-6/classes.html

Using the following Python script:
[kitswas/qt-class-extract.py](https://gist.github.com/kitswas/9b16c951dfe2d13ff2329ea2b6b2b573)

Closes #152.

### CODE REVIEW

**Comment by kitswas** [comment]
There are 1805 items in the set.  
I'm sorry for the spectacle.

**Comment by kitswas** [comment]
Closes #152

**Comment by kitswas** [comment]
@peti2001 Would you like to say something?

**Comment by peti2001** [comment]
Thanks for the improvement

**Pull request merged**
