### PR TITLE
Add Bootstrap when inclueded as Yii Asset

### PR DESCRIPTION
**Pull request by glpzzz**

### CODE REVIEW

**Comment by peti2001** [comment]
Hi @glpzzz,

I had a look at the change and I am not sure it will detect Bootstrap. Can you please share an example import, this is supposed to detect?

**Comment by glpzzz** [comment]
When importing bootstrap or other assets in Yii, normally you setup an asset bundle with your custom assets file names and specify 3rd party vendors (as Bootstrap) in the depends section. Check the example code in  https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#defining-asset-bundles

**Comment by glpzzz** [comment]
Sorry, I forgot to tell that I'm assuming this will also work when including the 'yii\bootstrap4\BootstrapAsset' or 'yii\bootstrap4\BootstrapPluginAsset'. Don't know if a separate rule needs to be included

**Comment by peti2001** [comment]
The line you added is part of the `CSS` language. This means only CSS files will be parsed to check this. But we cannot move this to the `PHP` part because then Bootstrap would be recognized as a PHP library.
I am afraid of the way it works cannot support this use case (detect a CSS library in PHP).

**Pull request closed without merging**
